SET IDENTITY_INSERT [dbo].[SIS_Localidades] ON;

MERGE INTO [dbo].[SIS_Localidades] AS Target
USING (
    VALUES
        (1, 2, N'Adolfo Alsina'),
        (2, 2, N'Adolfo Gonzales Chaves'),
        (3, 2, N'Alberti'),
        (4, 2, N'Almirante Brown'),
        (5, 2, N'Arrecifes'),
        (6, 2, N'Avellaneda'),
        (7, 2, N'Ayacucho'),
        (8, 2, N'Azul'),
        (9, 2, N'Bahía Blanca'),
        (10, 2, N'Balcarce'),
        (11, 2, N'Baradero'),
        (12, 2, N'Benito Juárez'),
        (13, 2, N'Berazategui'),
        (14, 2, N'Berisso'),
        (15, 2, N'Bolívar'),
        (16, 2, N'Bragado'),
        (17, 2, N'Brandsen'),
        (18, 2, N'Campana'),
        (19, 2, N'Cañuelas'),
        (20, 2, N'Capitán Sarmiento'),
        (21, 2, N'Carlos Casares'),
        (22, 2, N'Carlos Tejedor'),
        (23, 2, N'Carmen de Areco'),
        (24, 2, N'Castelli'),
        (25, 2, N'Chacabuco'),
        (26, 2, N'Chascomús'),
        (27, 2, N'Chivilcoy'),
        (28, 2, N'Colón'),
        (29, 2, N'Coronel de Marina Leonardo Rosales'),
        (30, 2, N'Coronel Dorrego'),
        (31, 2, N'Coronel Pringles'),
        (32, 2, N'Coronel Suárez'),
        (33, 2, N'Daireaux'),
        (34, 2, N'Dolores'),
        (35, 2, N'Ensenada'),
        (36, 2, N'Escobar'),
        (37, 2, N'Esteban Echeverría'),
        (38, 2, N'Exaltación de la Cruz'),
        (39, 2, N'Ezeiza'),
        (40, 2, N'Florencio Varela'),
        (41, 2, N'Florentino Ameghino'),
        (42, 2, N'General Alvarado'),
        (43, 2, N'General Alvear'),
        (44, 2, N'General Arenales'),
        (45, 2, N'General Belgrano'),
        (46, 2, N'General Guido'),
        (47, 2, N'General Juan Madariaga'),
        (48, 2, N'General La Madrid'),
        (49, 2, N'General Las Heras'),
        (50, 2, N'General Lavalle'),
        (51, 2, N'General Paz'),
        (52, 2, N'General Pinto'),
        (53, 2, N'General Pueyrredón'),
        (54, 2, N'General Rodríguez'),
        (55, 2, N'General San Martín'),
        (56, 2, N'General Viamonte'),
        (57, 2, N'General Villegas'),
        (58, 2, N'Guaminí'),
        (59, 2, N'Hipólito Yrigoyen'),
        (60, 2, N'Hurlingham'),
        (61, 2, N'Ituzaingó'),
        (62, 2, N'José C. Paz'),
        (63, 2, N'Junín'),
        (64, 2, N'La Costa'),
        (65, 2, N'La Matanza'),
        (66, 2, N'La Plata'),
        (67, 2, N'Lanús'),
        (68, 2, N'Laprida'),
        (69, 2, N'Las Flores'),
        (70, 2, N'Leandro N. Alem'),
        (71, 2, N'Lezama'),
        (72, 2, N'Lincoln'),
        (73, 2, N'Lobería'),
        (74, 2, N'Lobos'),
        (75, 2, N'Lomas de Zamora'),
        (76, 2, N'Luján'),
        (77, 2, N'Magdalena'),
        (78, 2, N'Maipú'),
        (79, 2, N'Malvinas Argentinas'),
        (80, 2, N'Mar Chiquita'),
        (81, 2, N'Marcos Paz'),
        (82, 2, N'Mercedes'),
        (83, 2, N'Merlo'),
        (84, 2, N'Monte'),
        (85, 2, N'Monte Hermoso'),
        (86, 2, N'Moreno'),
        (87, 2, N'Morón'),
        (88, 2, N'Navarro'),
        (89, 2, N'Necochea'),
        (90, 2, N'Nueve de Julio'),
        (91, 2, N'Olavarría'),
        (92, 2, N'Patagones'),
        (93, 2, N'Pehuajó'),
        (94, 2, N'Pellegrini'),
        (95, 2, N'Pergamino'),
        (96, 2, N'Pila'),
        (97, 2, N'Pilar'),
        (98, 2, N'Pinamar'),
        (99, 2, N'Presidente Perón'),
        (100, 2, N'Puán'),
        (101, 2, N'Punta Indio'),
        (102, 2, N'Quilmes'),
        (103, 2, N'Ramallo'),
        (104, 2, N'Rauch'),
        (105, 2, N'Rivadavia'),
        (106, 2, N'Rojas'),
        (107, 2, N'Roque Pérez'),
        (108, 2, N'Saavedra'),
        (109, 2, N'Saladillo'),
        (110, 2, N'Salliqueló'),
        (111, 2, N'Salto'),
        (112, 2, N'San Andrés de Giles'),
        (113, 2, N'San Antonio de Areco'),
        (114, 2, N'San Cayetano'),
        (115, 2, N'San Fernando'),
        (116, 2, N'San Isidro'),
        (117, 2, N'San Miguel'),
        (118, 2, N'San Nicolás'),
        (119, 2, N'San Pedro'),
        (120, 2, N'San Vicente'),
        (121, 2, N'Suipacha'),
        (122, 2, N'Tandil'),
        (123, 2, N'Tapalqué'),
        (124, 2, N'Tigre'),
        (125, 2, N'Tordillo'),
        (126, 2, N'Tornquist'),
        (127, 2, N'Trenque Lauquen'),
        (128, 2, N'Tres Arroyos'),
        (129, 2, N'Tres de Febrero'),
        (130, 2, N'Tres Lomas'),
        (131, 2, N'Vicente López'),
        (132, 2, N'Villa Gesell'),
        (133, 2, N'Villarino'),
        (134, 2, N'Zárate'),
        (135, 2, N'25 de Mayo')
) AS Source (NewLocId, NewLocPrvId, NewLocNombre)
ON Target.[loc_id] = Source.NewLocId

WHEN MATCHED THEN
    UPDATE SET
        Target.[loc_prv_id] = Source.NewLocPrvId,
        Target.[loc_nombre] = Source.NewLocNombre

WHEN NOT MATCHED BY TARGET THEN
    INSERT (
        [loc_id],
        [loc_prv_id],
        [loc_nombre]
    )
    VALUES (
        Source.NewLocId,
        Source.NewLocPrvId,
        Source.NewLocNombre
    );

SET IDENTITY_INSERT [dbo].[SIS_Localidades] OFF;