CREATE TABLE [dbo].[Ubicaciones_Logisticas] (
    [ubilog_id]                  INT             IDENTITY (1, 1) NOT NULL,
    [ubilog_codigo]              NVARCHAR (30)   NULL,
    [ubilog_tubilog_id]          INT             NULL,
    [ubilog_tmanilog_id]         INT             NULL,
    [ubilog_trotlog_id]          INT             NULL,
    [ubilog_teubilog_id]         INT             NULL,
    [ubilog_zonlog_id]           INT             NULL,
    [ubilog_secuencia_ruta]      NVARCHAR (50)   NULL,
    [ubilog_planta_id]           INT             NULL,
    [ubilog_depo_id]             INT             NULL,
    [ubilog_pasillo_id]          INT             NULL,
    [ubilog_deprack_id]          INT             NULL,
    [ubilog_posicion]            INT             NULL,
    [ubilog_columna]             INT             NULL,
    [ubilog_nivel]               NVARCHAR (10)   NULL,
    [ubilog_coord_x]             DECIMAL (18, 2) NULL,
    [ubilog_coord_y]             DECIMAL (18, 2) NULL,
    [ubilog_coord_z]             DECIMAL (18, 2) NULL,
    [ubilog_altura]              DECIMAL (18, 2) NULL,
    [ubilog_longitud]            DECIMAL (18, 2) NULL,
    [ubilog_anchura]             DECIMAL (18, 2) NULL,
    [ubilog_capacidad_cubica]    DECIMAL (18, 2) NULL,
    [ubilog_capacidad_maxima]    DECIMAL (18, 2) NULL,
    [ubilog_volumen_maximo]      DECIMAL (18, 2) NULL,
    [ubilog_peso_maximo]         DECIMAL (18, 2) NULL,
    [ubilog_tipo_producto_permitido] NVARCHAR (100) NULL,
    [ubilog_multiples_articulos] BIT             NULL,
    [ubilog_multiples_lotes]     BIT             NULL,
    [ubilog_usu_id_alta]         INT             NULL,
    [ubilog_fec_alta]            DATETIME        NULL,
    [ubilog_usu_id_mod]          INT             NULL,
    [ubilog_fec_mod]             DATETIME        NULL,
    [ubilog_activo]              BIT             NULL,
    CONSTRAINT [PK_Ubicaciones_Logisticas] PRIMARY KEY CLUSTERED ([ubilog_id] ASC),
    CONSTRAINT [FK_Ubicaciones_Logisticas_Depositos] FOREIGN KEY ([ubilog_depo_id]) REFERENCES [dbo].[Depositos] ([depo_id]),
    CONSTRAINT [FK_Ubicaciones_Logisticas_Depositos_Pasillos] FOREIGN KEY ([ubilog_pasillo_id]) REFERENCES [dbo].[Depositos_Pasillos] ([depopas_id])
);

